# Generated by Django 5.1.1 on 2024-09-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
