# Generated by Django 5.1.1 on 2024-10-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realworld', '0004_tag_article_customuser_favorite_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
